probes:
  ReplicasHighProbe:
    alias: kube-znn.replicasHigh.probe
    location: 127.0.0.1
    type: java
    javaInfo:
      class: br.unifor.kubow.probes.PrometheusProbe
      period: 5000
      args.length: 4
      args.0: "default"
      args.1: "kube-znn"
      args.2: "replicasHigh"
      args.3: "count(kube_pod_container_info{image=\"cmendes/znn:600k\"})"
  
  ReplicasMidProbe:
    alias: kube-znn.replicasMid.probe
    location: 127.0.0.1
    type: java
    javaInfo:
      class: br.unifor.kubow.probes.PrometheusProbe
      period: 5000
      args.length: 4
      args.0: "default"
      args.1: "kube-znn"
      args.2: "replicasMid"
      args.3: "count(kube_pod_container_info{image=\"cmendes/znn:400k\"})"
   
  ReplicasLowProbe:
    alias: kube-znn.replicasLow.probe
    location: 127.0.0.1
    type: java
    javaInfo:
      class: br.unifor.kubow.probes.PrometheusProbe
      period: 5000
      args.length: 4
      args.0: "default"
      args.1: "kube-znn"
      args.2: "replicasLow"
      args.3: "count(kube_pod_container_info{image=\"cmendes/znn:100k\"})"

  SloProbe2:
    alias: kube-znn.slo.probe
    location: 127.0.0.1
    type: java
    javaInfo:
      class: br.unifor.kubow.probes.PrometheusProbe
      period: 5000
      args.length: 4
      args.0: "default"
      args.1: "kube-znn"
      args.2: "slo"
      args.3: "sum(rate(request_duration_seconds_bucket{le=\"00.010\"}[30s])) / sum(rate(request_duration_seconds_count[30s]))"

  DeploymentPropertiesProbe:
    alias: deployments.default.kube-znn.probe
    location: 127.0.0.1
    type: java
    javaInfo:
      class: br.unifor.kubow.probes.DeploymentInfoProbe
      period: 5000
      args.length: 2
      args.0: "default"
      args.1: "kube-znn"
